#!/bin/bash

MAIN_DIR="intersection_sim"

run_dir="runs"
agent="NeuralQLearner"
n_replay=1
netfile=""
update_freq=4
actrep=1
discount=0.99
seed=1
learn_start=50000
initial_priority="false"
replay_memory=100000
eps_end=0.1
eps_endt=replay_memory
lr=0.00025
agent_type="DQN_VEHICLE"
preproc_net=""
agent_name=$agent_type"_FULL_Y"
state_dim=8
ncols=1
agent_params="lr="$lr",ep=1,ep_end="$eps_end",ep_endt="$eps_endt",discount="$discount",hist_len=4,learn_start="$learn_start",replay_memory="$replay_memory",update_freq="$update_freq",n_replay="$n_replay",network="$netfile",preproc="$preproc_net",state_dim="$state_dim",minibatch_size=32,rescale_r=1,bufferSize=256,valid_size=500,target_q=10000,clip_delta=1,min_reward=-1,max_reward=1"
steps=5000000
eval_freq=25000
eval_steps=12500
prog_freq=500
save_freq=12500
gpu=-1
random_starts=30
num_threads=4

args="-run_dir $run_dir -name $agent_name -agent $agent -agent_params $agent_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -seed $seed -threads $num_threads"
echo $args

cd $MAIN_DIR
luajit train_agent.lua $args
